[build]
  publish = "."
  
[build.environment]
  NODE_VERSION = "16"

# Redirect for admin
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

# Form handling
[[redirects]]
  from = "/contact"
  to = "/contact-success.html"
  status = 200
  conditions = {Role = ["form-submission"]}

# 404 redirect
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404